name: virtual_tourism
description: "tourism but virtual"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  cloud_firestore: ^5.0.2
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_storage: ^12.3.3
  firebase_app_check: ^0.3.1+3
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.1.0
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.6
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  panorama_viewer: ^1.0.3
  flutter_svg: ^2.0.10+1
  email_validator: ^3.0.0
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  image: ^4.3.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - .env
    - assets/
    - assets/icons/
    - assets/images/
    - assets/images/thumbs/
