name: virtual_tourism
description: "tourism but virtual"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase 🔥
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  firebase_app_check: ^0.3.2+4

  # State Management
  provider: ^6.1.2

  # UI Packages
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.7
  panorama_viewer: ^2.0.3
  flutter_svg: ^2.0.17
  popover: ^0.3.1

  # Image & Storage
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  image: ^4.5.3

  # Firebase Tools
  google_sign_in: ^6.2.2
  shared_preferences: ^2.5.2
  email_validator: ^3.0.0

  # Utilities
  url_launcher: ^6.3.1
  share_plus: ^10.1.4
  intl: ^0.20.2
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Icon Generator
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 23
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#ffffff"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 128
  macos:
    generate: true
    image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  generate: true

  assets:
    - .env
    - assets/
    - assets/icons/
